CREATE TABLE IF NOT EXISTS restaurants (
    rest_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rest_name text NOT NULL,
    cuisine text NOT NULL,
    address_building_number integer NOT NULL,
    address_street text NOT NULL,
    address_zipcode integer NOT NULL,
    city text NOT NULL,
    rest_state text NOT NULL,
    phone_number text NOT NULL,
    rest_image text,
    link text NOT NULL
);

CREATE TABLE IF NOT EXISTS nightlife (
    club_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    club_name text NOT NULL,
    address_building_number integer NOT NULL,
    address_street text NOT NULL,
    address_zipcode integer NOT NULL,
    city text NOT NULL,
    club_state text NOT NULL,
    phone_number text,
    entry_age integer NOT NULL,
    adult boolean NOT NULL,
    area text NOT NULL,
    club_image text
);